/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PollServerInterfaceClient.java
 *
 * Created on Sep 26, 2011, 12:16:08 AM
 */

package com.yzhang;

/**
 *
 * @author yunzhang
 */

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.*;
import java.rmi.server.*;

public class PollServerInterfaceClient extends javax.swing.JApplet implements VoteCallbackInterface{


    private PollServerInterface poll;
   // private PollServerInterfaceImpl pollImpl;


    private boolean isStandalone=true;
    private int Cyes=0,Cno=0,Cnocare=0;
 
    /** Initializes the applet PollServerInterfaceClient */
    public void init() {
       
        //initializeRMI()
       super.init();
        try {
            

            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        try{
   
               String host="";
         

              if(!isStandalone) host = getCodeBase().getHost();

             
                 System.out.println( "Exporting the Applet" );
                 UnicastRemoteObject.exportObject(this);
               
                 Registry registry =LocateRegistry.getRegistry(host);
                 
                 poll =(PollServerInterface) registry.lookup("PollServerInterfaceImpl");
                 
                 System.out.println("Server object"+poll+"found");
                 poll.addCallback(this);
                 System.out.println( "We have been registered!" );

              }catch(Exception ex){

                    System.out.println(ex);
              }
              
   
    }
  
    private void sendVote(int yes, int no, int nocare)        //user send votes
    {
        try
        {
          poll.ReceiveCounts(yes, no, nocare);
          
        }catch(Exception ex)
         {
          ex.printStackTrace();
        }
    }

    private void requestCurrent()             //user request current counts
    {
    

     try{
        int a[]=new int[3];
        a=poll.RequestVote();
        jtfYes.setText(new Integer(a[0]).toString());
        jtfNo.setText(new Integer(a[1]).toString());
        jtfNocare.setText(new Integer(a[2]).toString());

    }catch(Exception ex)
    {ex.printStackTrace();}

    }
  
    public void callVotes(int yes)             //using callback to get the number of yes
   {    
        jtfYesm10.setText(new Integer(yes).toString());
    
    }
  
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        bgSendvote = new javax.swing.ButtonGroup();
        jplSendVote = new javax.swing.JPanel();
        jbtSendvote = new javax.swing.JButton();
        jrbYes = new javax.swing.JRadioButton();
        jrbNo = new javax.swing.JRadioButton();
        jrbNocare = new javax.swing.JRadioButton();
        JplCountsInfo = new javax.swing.JPanel();
        jbtRequest = new javax.swing.JButton();
        jtfYes = new javax.swing.JTextField();
        jtfNo = new javax.swing.JTextField();
        jtfNocare = new javax.swing.JTextField();
        jlbYes = new javax.swing.JLabel();
        jlbNo = new javax.swing.JLabel();
        JlbNocare = new javax.swing.JLabel();
        jlbYesm10 = new javax.swing.JLabel();
        jtfYesm10 = new javax.swing.JTextField();

        jFrame1.setBounds(new java.awt.Rectangle(700, 700, 800, 600));

        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(500, 300));

        jplSendVote.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Send Vote"));

        jbtSendvote.setText("Send Vote");
        jbtSendvote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtSendvoteMouseClicked(evt);
            }
        });
        jbtSendvote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSendvoteActionPerformed(evt);
            }
        });

        bgSendvote.add(jrbYes);
        jrbYes.setText("Yes");

        bgSendvote.add(jrbNo);
        jrbNo.setText("No");

        bgSendvote.add(jrbNocare);
        jrbNocare.setText("No Care");

        org.jdesktop.layout.GroupLayout jplSendVoteLayout = new org.jdesktop.layout.GroupLayout(jplSendVote);
        jplSendVote.setLayout(jplSendVoteLayout);
        jplSendVoteLayout.setHorizontalGroup(
            jplSendVoteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jplSendVoteLayout.createSequentialGroup()
                .addContainerGap()
                .add(jrbYes)
                .add(19, 19, 19)
                .add(jrbNo)
                .add(18, 18, 18)
                .add(jrbNocare)
                .add(42, 42, 42)
                .add(jbtSendvote)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jplSendVoteLayout.setVerticalGroup(
            jplSendVoteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jplSendVoteLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jplSendVoteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jrbYes)
                    .add(jrbNocare)
                    .add(jrbNo)
                    .add(jbtSendvote))
                .add(28, 28, 28))
        );

        JplCountsInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Counts Info"));

        jbtRequest.setText("Request Current Counts");
        jbtRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtRequestMouseClicked(evt);
            }
        });

        jtfYes.setEditable(false);
        jtfYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfYesActionPerformed(evt);
            }
        });

        jtfNo.setEditable(false);
        jtfNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNoActionPerformed(evt);
            }
        });

        jtfNocare.setEditable(false);
        jtfNocare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNocareActionPerformed(evt);
            }
        });

        jlbYes.setText("Yes:");

        jlbNo.setText("No:");

        JlbNocare.setText("Not Care:");

        org.jdesktop.layout.GroupLayout JplCountsInfoLayout = new org.jdesktop.layout.GroupLayout(JplCountsInfo);
        JplCountsInfo.setLayout(JplCountsInfoLayout);
        JplCountsInfoLayout.setHorizontalGroup(
            JplCountsInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JplCountsInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(JplCountsInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jbtRequest)
                    .add(JplCountsInfoLayout.createSequentialGroup()
                        .add(jlbYes)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(42, 42, 42)
                        .add(jlbNo)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(27, 27, 27)
                .add(JlbNocare)
                .add(2, 2, 2)
                .add(jtfNocare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        JplCountsInfoLayout.setVerticalGroup(
            JplCountsInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JplCountsInfoLayout.createSequentialGroup()
                .add(jbtRequest)
                .add(18, 18, 18)
                .add(JplCountsInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtfNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbYes)
                    .add(jlbNo)
                    .add(JlbNocare)
                    .add(jtfNocare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbYesm10.setText("The Number of \"Yes\" has reached to:");

        jtfYesm10.setEditable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jlbYesm10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfYesm10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jplSendVote, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(JplCountsInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jplSendVote, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(JplCountsInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbYesm10)
                    .add(jtfYesm10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSendvoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtSendvoteMouseClicked
        // TODO add your handling code here:
        if(jrbYes.isSelected())
            Cyes=1;
        else if(jrbNo.isSelected())
            Cno=1;
        else if(jrbNocare.isSelected())
            Cnocare=1;
        sendVote(Cyes, Cno, Cnocare);
        
        Cyes=0;Cno=0;Cnocare=0;
        
   
    }//GEN-LAST:event_jbtSendvoteMouseClicked

    private void jbtSendvoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSendvoteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jbtSendvoteActionPerformed

    private void jbtRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtRequestMouseClicked
        // TODO add your handling code here:

        requestCurrent();
}//GEN-LAST:event_jbtRequestMouseClicked

    private void jtfYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfYesActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtfYesActionPerformed

    private void jtfNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtfNoActionPerformed

    private void jtfNocareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNocareActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jtfNocareActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbNocare;
    private javax.swing.JPanel JplCountsInfo;
    private javax.swing.ButtonGroup bgSendvote;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton jbtRequest;
    private javax.swing.JButton jbtSendvote;
    private javax.swing.JLabel jlbNo;
    private javax.swing.JLabel jlbYes;
    private javax.swing.JLabel jlbYesm10;
    private javax.swing.JPanel jplSendVote;
    private javax.swing.JRadioButton jrbNo;
    private javax.swing.JRadioButton jrbNocare;
    private javax.swing.JRadioButton jrbYes;
    private javax.swing.JTextField jtfNo;
    private javax.swing.JTextField jtfNocare;
    private javax.swing.JTextField jtfYes;
    private javax.swing.JTextField jtfYesm10;
    // End of variables declaration//GEN-END:variables

}
